# Use an official Java runtime as a parent image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /endura_app

# Copy the Gradle build files
COPY build.gradle settings.gradle gradlew ./
COPY gradle ./gradle

# Copy the source code into the container
COPY src ./src

# Build the application
RUN ./gradlew build --no-daemon

# Copy the JAR file to the container
COPY build/libs/endura-0.0.1-SNAPSHOT.jar /endura_app/endura.jar

# Set the command to run your application
CMD ["java", "-jar", "/endura_app/endura.jar"]
