name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('endura/**/*.gradle*', 'endura/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: List files in the endura directory with permissions
      run: ls -l endura

    - name: Print working directory
      run: pwd

    - name: Grant execute permission for gradlew
      run: chmod +x endura/gradlew

    - name: Build with Gradle
      run: ./endura/gradlew build --no-daemon
      working-directory: endura

    - name: Run unit tests
      run: ./endura/gradlew test --no-daemon
      working-directory: endura

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Trigger deployment to Render
      env:
        RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
      run: |
        echo "Triggering deployment to Render..."
        curl -X POST $RENDER_DEPLOY_HOOK
